"""Generate the interactive 3Dmol.js selection widget for the docs.

Run in the atomworks ``.venv`` (needs ``PDB_MIRROR_PATH`` set):

    python gen_interactive.py docs/_static/selection/interactive.html

Produces a single self-contained HTML fragment: **one** 3Dmol.js viewer plus a row of buttons
that toggle between selection strings. Each button updates the description text and re-highlights
the same viewer. Highlights are driven by the real ``atom_array.mask(...)`` output mapped to atom
serials, so what you see is exactly what the selection selects - including the coordinate-predicate
example that a viewer's own selection language could not express.

Interactivity: pick a syntax with the buttons; drag to rotate, scroll to zoom, click a highlighted
atom to label it.
"""

import json
import sys
from pathlib import Path

import biotite.structure as struc
import biotite.structure.io.pdb as pdb
import numpy as np
from biotite.structure import AtomArray

from atomworks.io.utils.io_utils import load_any
from atomworks.io.utils.testing import get_pdb_path

PDB_ID = "1ycr"  # MDM2 (chain A) in complex with the p53 transactivation peptide (chain B)
THREEDMOL_SRC = "https://cdn.jsdelivr.net/npm/3dmol@2.4.2/build/3Dmol-min.js"


def presets(atom_array: AtomArray) -> list[dict]:
    """Toggle-able selections. ``expr`` is a real query string; ``style`` picks the highlight look."""
    z0 = float(np.median(atom_array.coord[atom_array.atom_name == "CA", 2]))
    return [
        {
            "label": "Whole chain",
            "expr": "sel('B')",
            "desc": "A bare chain id selects every atom of that chain - here the p53 peptide (chain B).",
            "style": "stick",
        },
        {
            "label": "One residue",
            "expr": "sel('B/TRP')",
            "desc": "chain / residue-name: a single tryptophan, small enough to see every atom.",
            "style": "stick",
        },
        {
            "label": "Residue-type list",
            "expr": "sel('B/[PHE,TRP,LEU]')",
            "desc": "[ ... ] is a within-field list - any of these residue names (the p53 anchor residues).",
            "style": "stick",
        },
        {
            "label": "Residue range",
            "expr": "sel('A/*/[25-35]')",
            "desc": "[lo-hi] is an inclusive residue-id range. Ranges must be bracketed.",
            "style": "stick",
        },
        {
            "label": "Atom-name list",
            "expr": "sel('A/*/*/[N,CA,C,O]')",
            "desc": "[ ... ] on the atom field selects just these atoms - the protein backbone.",
            "style": "stick",
        },
        {
            "label": "List and predicate",
            "expr": f"sel('[A,B]/*/*/CA') & (z > {z0:.2f})",
            "desc": "sel(...) composes inside a query: Ca of both chains, intersected with a coordinate cutoff.",
            "style": "sphere",
        },
    ]


HTML = """<!-- Generated by docs/io/utils/_render_selection_examples/gen_interactive.py -->
<script src="{src}"></script>
<style>
  .sel-widget {{ border: 1px solid var(--pst-color-border, #ccc); border-radius: 8px; overflow: hidden;
                margin: 1rem 0; }}
  .sel-controls {{ display: flex; flex-wrap: wrap; gap: 0.4rem; padding: 0.7rem;
                  background: var(--pst-color-surface, #f4f4f4); }}
  .sel-controls button {{ border: 1px solid var(--pst-color-border, #bbb); border-radius: 999px;
    background: var(--pst-color-on-surface, #fff); color: inherit; padding: 0.25rem 0.8rem;
    font-size: 0.85em; cursor: pointer; }}
  .sel-controls button.active {{ background: #e8850c; border-color: #e8850c; color: #fff; }}
  .sel-desc {{ padding: 0.7rem 0.9rem; border-top: 1px solid var(--pst-color-border, #eee); }}
  .sel-desc code {{ font-weight: 600; }}
  .sel-desc-text {{ font-size: 0.9em; opacity: 0.85; margin-top: 0.25rem; }}
  .sel-viewer {{ position: relative; width: 100%; height: 420px; }}
  .sel-hint {{ font-size: 0.78em; opacity: 0.6; padding: 0.3rem 0.9rem; }}
</style>
<div class="sel-widget">
  <div class="sel-controls" id="sel-controls"></div>
  <div class="sel-desc"><code id="sel-expr"></code><div class="sel-desc-text" id="sel-text"></div></div>
  <div class="sel-viewer" id="sel-viewer"></div>
  <div class="sel-hint">pick a syntax above · drag to rotate · scroll to zoom · click a highlighted atom to label it</div>
</div>
<script>
(function() {{
  var PDB = {pdb_json};
  var PRESETS = {presets_json};
  var viewer = $3Dmol.createViewer(document.getElementById("sel-viewer"), {{backgroundColor: "white"}});
  var model = viewer.addModel(PDB, "pdb");
  var atoms = model.selectedAtoms({{}});

  var controls = document.getElementById("sel-controls");
  var buttons = PRESETS.map(function(ex, i) {{
    var b = document.createElement("button");
    b.textContent = ex.label;
    b.onclick = function() {{ apply(i); }};
    controls.appendChild(b);
    return b;
  }});

  function apply(i) {{
    var ex = PRESETS[i];
    var serials = ex.idxs.map(function(k) {{ return atoms[k].serial; }});
    var sel = {{serial: serials}};
    viewer.removeAllLabels();
    viewer.setStyle({{}}, {{cartoon: {{color: "lightgrey", opacity: 0.55}}}});
    if (ex.style === "sphere") {{
      viewer.addStyle(sel, {{sphere: {{scale: 0.30, color: "orange"}}}});
    }} else {{
      viewer.addStyle(sel, {{stick: {{radius: 0.18, colorscheme: "orangeCarbon"}},
                             sphere: {{scale: 0.18, colorscheme: "orangeCarbon"}}}});
      viewer.addStyle(sel, {{cartoon: {{color: "orange"}}}});
    }}
    viewer.setClickable(sel, true, function(atom) {{
      viewer.addLabel(atom.chain + " . " + atom.resn + atom.resi + " . " + atom.atom,
        {{position: atom, backgroundColor: "0x1b1b1b", backgroundOpacity: 0.85,
          fontColor: "white", fontSize: 11}});
      viewer.render();
    }});
    document.getElementById("sel-expr").textContent = ex.expr;
    document.getElementById("sel-text").textContent = ex.desc;
    buttons.forEach(function(b, j) {{ b.className = j === i ? "active" : ""; }});
    viewer.zoomTo(sel, 400);
    viewer.render();
  }}
  apply(0);
}})();
</script>
"""


def main(out_path: Path) -> None:
    atom_array = load_any(get_pdb_path(PDB_ID), model=1)

    # Write the structure once as a PDB string (serials are sequential 1..N in array order).
    plain = struc.AtomArray(atom_array.array_length())
    plain.coord = atom_array.coord
    for annot in ("chain_id", "res_id", "res_name", "atom_name", "element"):
        if annot in atom_array.get_annotation_categories():
            plain.set_annotation(annot, atom_array.get_annotation(annot))
    tmp = out_path.parent / "_tmp_structure.pdb"
    f = pdb.PDBFile()
    f.set_structure(plain)
    f.write(str(tmp))
    pdb_string = tmp.read_text()
    tmp.unlink()

    configs = []
    for ex in presets(atom_array):
        mask = atom_array.mask(ex["expr"])  # <-- the actual feature under test
        idxs = [int(v) for v in np.where(mask)[0]]
        assert idxs, f"{ex['expr']!r} selected no atoms"
        configs.append({**ex, "idxs": idxs})
        print(f"{ex['label']:>18}: {len(idxs):>4d} atoms  <- {ex['expr']}")

    html = HTML.format(src=THREEDMOL_SRC, pdb_json=json.dumps(pdb_string), presets_json=json.dumps(configs))
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(html)
    print(f"wrote {out_path} ({len(html) // 1024} KB, {len(configs)} presets, 1 viewer)")


if __name__ == "__main__":
    main(Path(sys.argv[1]))
