name: Lab validation

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test_digs:
    if: github.repository == 'baker-laboratory/atomworks-dev'
    runs-on: [self-hosted]
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - name: Run full tests on lab infrastructure
        env:
          ATOMWORKS_CI_CONTAINER: ${{ vars.ATOMWORKS_CI_CONTAINER }}
          ATOMWORKS_CI_TEST_PACK: ${{ vars.ATOMWORKS_CI_TEST_PACK }}
          N_CPU: '8'
        run: srun --chdir="$PWD" -p cpu -c "$N_CPU" -t 00:40:00 --mem=32G bash .github/ci/run_tests.sh
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lab-coverage
          path: coverage.xml
